name: Build Windows EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:   # allows you to trigger manually

jobs:
  build-windows-exe:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build EXE with PyInstaller
        run: |
          # Run as module so package imports work
          pyinstaller --onefile --name ac_workshop.exe -m ac_workshop.main

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: ac_workshop-exe
          path: dist/ac_workshop.exe
